import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Menu from '@/components/Menu';

export default function About() {
    return (
        <>
        <Head>
          <title>Jennifer Gaupel - About</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>      
        <main className={styles.main}>
          <Menu></Menu>
          <div className='about'>
            <p>
              I am a software engineer with 5 years experience. I enjoy working collaboratively and digging into difficult problems to provide the best solution based on the needs of the company. 
              I enjoy learning new languages and technologies. Right now I am looking to grow my skills as a developer while also contributing to a team. 
              I worked in quality assurance for 4 years prior to becoming a developer. I have a passion for quality and testing, and I always approach my work with the end user in mind.
              <br/>
              <br/>
              Outside of the workplace, I am passionate about women in tech! I have participated in our local Girl Develop It program. 
              I am also committed to mutual aid within my community. My current passion project is a community resource finder, 
              cincinnaticommunityresources.com, which facilitates finding Cincinnati resources for people to either give or receive aid.
            </p>              
          </div>
        </main>
      </>
    )
}