import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Menu from '@/components/Menu';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {faLinkedin, faGithub} from '@fortawesome/free-brands-svg-icons'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        {/* Google tag (gtag.js) */}
        {/* <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143913681-1"></script>
        <script>          
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-143913681-1');
        </script> */}
        <title>Jennifer Gaupel - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <main className={styles.main}>
        <Menu></Menu>
        <div>
            <Image
              src="/jennifer.jpg"
              alt="Photo of Jennifer Gaupel"
              className="profile-pic"
              width={180}
              height={220}
              priority
            />            
        </div>
        <div>
          <p>Jennifer Gaupel</p>
          <br/>
          <p>Software Engineer | Cat Enthusiast</p>                    
          <br/>
          <p >Cincinnati, OH</p>
          <br/>
          <p>
            <a className="icon-link" href="https://github.com/JenniferGaupel" target={'_blank'} rel={'noreferrer'}>
              <FontAwesomeIcon
                icon={faGithub} style={{fontSize: 30}}
              />
            </a>
            <a className="icon-link" href="https://www.linkedin.com/in/jennifergaupel/" target={'_blank'} rel={'noreferrer'}>
              <FontAwesomeIcon
                icon={faLinkedin} style={{fontSize: 30}}
              />
            </a>
          </p>
        </div>
      </main>
    </>
  )
}
